include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/${VCPKG_TARGET_TRIPLET}.toolchain.common.cmake")

find_program(LLD-LINK_EXECUTBALE NAMES "lld-link" "lld-link.exe" PATHS ENV LLVMInstallDir PATH_SUFFIXES "bin" NO_DEFAULT_PATH)
find_program(LLD-LINK_EXECUTBALE NAMES "lld-link" "lld-link.exe" PATHS ENV LLVMInstallDir PATH_SUFFIXES "bin" )
get_filename_component(LLVM_BIN_DIR "${LLD-LINK_EXECUTBALE}" DIRECTORY)
list(INSERT CMAKE_PROGRAM_PATH 0 "${LLVM_BIN_DIR}")

# Set compiler.
set(CMAKE_C_COMPILER "cl.exe" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "cl.exe" CACHE STRING "" FORCE)
set(CMAKE_AR "${LLVM_BIN_DIR}/llvm-lib.exe" CACHE STRING "" FORCE)
set(CMAKE_LINKER "${LLD-LINK_EXECUTBALE}" CACHE STRING "" FORCE) 
#set(CMAKE_LINKER "link.exe" CACHE STRING "" FORCE)
set(CMAKE_ASM_MASM_COMPILER "ml64.exe" CACHE STRING "" FORCE)
set(CMAKE_RC_COMPILER "rc.exe" CACHE STRING "" FORCE)
set(CMAKE_MT "mt.exe" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS "${CMAKE_CL_NOLOGO} ${windows_defs} /W3 ${CHARSET_FLAG} ${VCPKG_C_FLAGS} ${std_c_flags}" CACHE STRING "")
set(CMAKE_C_FLAGS_DEBUG "/Zi /Ob0 /Od /RTC1 /D_DEBUG ${VCPKG_CRT_FLAG}d ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE "/O2 /Oi /Gy /Zi /DNDEBUG ${VCPKG_CRT_FLAG} ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")

set(CMAKE_CXX_FLAGS "${CMAKE_CL_NOLOGO} ${windows_defs} /W3 ${CHARSET_FLAG} /GR /EHsc ${VCPKG_CXX_FLAGS} ${std_cxx_flags}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "/Zi /Ob0 /Od /RTC1 /D_DEBUG ${VCPKG_CRT_FLAG}d ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "/O2 /Oi /Gy /Zi /DNDEBUG ${VCPKG_CRT_FLAG} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")

# Set linker flags.
foreach(LINKER SHARED_LINKER MODULE_LINKER EXE_LINKER)
  set(CMAKE_${LINKER}_FLAGS_INIT "${CMAKE_CL_NOLOGO} ${VCPKG_LINKER_FLAGS}")
  set(CMAKE_${LINKER}_FLAGS_DEBUG "/INCREMENTAL /DEBUG:FULL" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_RELEASE "/OPT:REF /OPT:ICF" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_MINSIZEREL "/OPT:REF /OPT:ICF" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_RELWITHDEBINFO "/OPT:REF /OPT:ICF /DEBUG:FULL" CACHE STRING "")
endforeach()

set(CMAKE_RC_FLAGS "-c65001 ${windows_defs}" CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/${VCPKG_TARGET_TRIPLET}.toolchain.common.unset.cmake")
